#!/bin/bash

#1、语言符号及其分类(LC_CTYPE)
#2、数字(LC_NUMERIC)
#3、比较和排序习惯(LC_COLLATE)
#4、时间显示格式(LC_TIME)
#5、货币单位(LC_MONETARY)
#6、信息主要是提示信息,错误信息,状态信息,标题,标签,按钮和菜单等(LC_MESSAGES)
#7、姓名书写方式(LC_NAME)
#8、地址书写方式(LC_ADDRESS)
#9、电话号码书写方式(LC_TELEPHONE)
#10、度量衡表达方式 (LC_MEASUREMENT)
#11、默认纸张尺寸大小(LC_PAPER)
#12、对locale自身包含信息的概述(LC_IDENTIFICATION)

locale
